{% set name = "river" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/online-ml/{{ name }}/archive/{{ version }}.tar.gz
  sha256: ea074d7c285112597a5d1ff3a76a763c9b3ab56f33b0cebdeebf37fd3432ea57

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pip
    - python
    - cython >=0.29.6
    - numpy >=1.16.4
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scikit-learn
    - scipy
    - cython >=0.29.6
    - pandas
    - dataclasses

test:
  imports:
    - river
    - river.anomaly
    - river.base
    - river.cluster
    - river.compat
    - river.compose
    - river.datasets
    - river.datasets.synth
    - river.drift
    - river.dummy
    - river.ensemble
    - river.evaluate
    - river.expert
    - river.facto
    - river.feature_extraction
    - river.feature_selection
    - river.imblearn
    - river.linear_model
    - river.meta
    - river.metrics
    - river.metrics.cluster
    - river.multiclass
    - river.multioutput
    - river.naive_bayes
    - river.neighbors
    - river.optim
    - river.optim.initializers
    - river.optim.losses
    - river.optim.schedulers
    - river.preprocessing
    - river.proba
    - river.reco
    - river.stats
    - river.stream
    - river.time_series
    - river.tree
    - river.tree.splitter
    - river.utils
    - river.utils.math
    - river.utils.pretty

about:
  home: https://github.com/online-ml/river
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: River is a Python library for online machine learning
  dev_url: https://github.com/online-ml/river

extra:
  recipe-maintainers:
    - mxr-conda
    - oblute
    - rluria14
