{% set name = "river" %}
{% set version = "0.21.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/river-{{ version }}.tar.gz
  sha256: 359d5e9b267b07e025f0dee1e2621c6fa587a73152054387a506877e2d8f68be

build:
  skip: true  # [py<39]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('rust') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools-rust
    - poetry-core >=1.0.0
    - numpy
    - cython
    - pip
  run:
    - python
    - scipy >=1.12.1,<2.0.0
    - pandas >=2.1.0,<3.0.0
    - {{ pin_compatible('numpy') }}

test:
  imports:
    - river
    - river._bandit
    - river.anomaly
    - river.base
    - river.checks
    - river.cluster
    - river.compat
    - river.compose
    - river.covariance
    - river.datasets
    - river.datasets.synth
    - river.drift
    - river.ensemble
    - river.evaluate
    - river.facto
    - river.feature_extraction
    - river.feature_selection
    - river.imblearn
    - river.linear_model
    - river.metrics
    - river.metrics.multioutput
    - river.misc
    - river.model_selection
    - river.multiclass
    - river.multioutput
    - river.naive_bayes
    - river.neighbors
    - river.neural_net
    - river.optim
    - river.preprocessing
    - river.proba
    - river.reco
    - river.rules
    - river.stats
    - river.stream
    - river.time_series
    - river.tree
    - river.tree.nodes
    - river.tree.split_criterion
    - river.tree.splitter
    - river.utils
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://riverml.xyz/
  summary: Online machine learning in Python
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/online-ml/river

extra:
  recipe-maintainers:
    - mxr-conda
    - bubblyorca
    - synapticarbors
